# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            unstack
tagline:          'Whatever gets the job done stack'
description:      'Follow me on twitter <a href="https://twitter.com/mukeshsoni" target="_blank">@mukeshsoni</a>.'
url:              http://unstack.in
baseurl:          /

author:
  name:           'Mukesh Soni'
  url:            http://unstack.in

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mukeshsoni
